config/routes.rb
Task3::Application.routes.draw do

  root :to => 'articles#index'

     get 'products' => 'catalog#view', as: :catalogue
     get 'profile' => 'articles#profile', as: :profile
     get 'contact' => 'articles#contact', as: :contact

     resources :articles
     resources :comments

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  has_attached_file :photo, :styles => { :thumb => "100x300", :original => "600x300"},
  :url => "/upload_images/:id/:style/:basename.:extension",
  :path => ":rails_root/public/upload_images/:id/:style/:basename.:extension"
  
  validates :title, presence: true, length: {minimum: 5}
  validates :content, presence: true, length: {minimum: 10}
  validates :status, presence: true
  validates_attachment_presence :photo
  validates_attachment_size :photo, :in => 0..200.kilobytes
  validates_attachment_content_type :photo, :content_type => ['image/pjpeg', 'image/jpg', 'image/jpeg', 'image/png']
  
  scope :status_active, -> {where(status: 'active')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.status_active
  end
  
  def show
    @article = Article.find_by_id(params[:id])
  end
  
  def edit
    @article = Article.find_by_id(params[:id])
  end
  
  def update
    @article = Article.find_by_id(params[:id])
    
    if @article.update(params_article)
      flash[:notice] = "Success Update Records"
      redirect_to action: 'index'
    else
      flash[:error] = "data cannot update"
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find_by_id(params[:id])
    
    if @article.destroy
      flash[:notice] = "Success Delete a Article"
      redirect_to action: 'index'
    else
      flash[:error] = "Fails delete article"
      redirect_to action: 'index'
    end
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params_article)
    
    if @article.save
      flash[:notice] = "Success Add Records"
      
      redirect_to action: 'index'
    else
      flash[:errors] = "Data not valid"
      render "new"
    end
  end
  
  private
  def params_article
    params.require(:article).permit(:title, :content, :status, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/contact.html.erb
<h1><%= @contact_name%> Contact</h1>

<!-- Content  -->
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h1> <%= @contact_name%></h1>
          	<%= image_tag("profile2.JPG", alt: "Image Pgofile", width: "140px", height: "140px", class: "img-circle") %>
          	
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
         	<%= form_tag("#", class: "form-horizontal") do %>
         		<div class="form-group">
         			<%= label_tag "inputEmail", "Email", class: "col-sm-2 control-label"%>
         			<div class="col-sm-10">
         				<%= text_field "person", "email", "id" => "inputEmail", "class" => "form-control", "placeholder" => "Email" %>
         			</div>
         		</div>
         		<div class="form-group">
         			<%= label_tag "inputMessage", "Messages", class: "col-sm-2 control-label" %>
         			<div class="col-sm-10">
         				<%= text_area "post", "messages", "rows" => 20, class: "form-control", placeholder: "Leave a messages" %>
         			</div>
         		</div>
         		<div class="form-group">
         			<div class="col-sm-10">
         				<%= button_tag "Send a Messages", class: "btn btn-default" %>
         			</div>
         		</div>
         	<% end %>
         </div>
        </div>
      </div>
    </div>

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>

<% if @article.errors.any? %>
	<strong><%= pluralize(@article.errors.count, 'error') %> found while saving images</strong>
	<ul>
		<% @article.errors.full_messages.each do |m|%>
			<li><%= m %></li>
		<% end %>
	</ul>
<% end %>

<%=  f.label :title%>
<%=  f.text_field :title%>

<br />

<%=  f.label :content%>
<%=  f.text_area :content, cols: 20, rows: 10%>

<br />

<%=  f.label :status%>
<%=  f.radio_button :status, "active"%>
<%=  label :article_status, 'Active'%>
<%=  f.radio_button :status, "off"%>
<%=  label :article_status, 'Off'%>

<br />

<p>Current Photo: <%= image_tag @article.photo.url(:thumb) %></p>
<%= f.label :photo%>
<%= f.file_field :photo%>

<br />

<%=  f.submit :submit%>
<% end  %>

<div>
	<%= link_to 'back to index', article_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h1 >Welcome to Task 4</h1>
</div>
<hr />
<div class="container">
<p class="btn btn-success"><%= link_to 'Add Article', new_article_path %></p>
</div>
<br />
<div class="container">
<% @articles.each do |article| %>
<div class="row">
	<div class="col-sm-2 col-md-2">
		<div class="thumbnail">
			<%= link_to (image_tag article.photo.url(:thumb)), article_path(article.id) %>
		<div class="caption">
			<strong><%= article.title %></strong>
			<p> 
				<%= article.content.truncate(20) %>
				<%= link_to 'read more', article_path(article.id)%>
			</p>
			<strong>status: <%= article.status %></strong>
			<p><span><%= link_to 'edit', edit_article_path(article.id)%></span>
			<span> | </span>
			<span><%= link_to 'delete', article_path(article.id), method: "DELETE", data: {confirm: 'Delete this article?'} %></span>
			</p>
		</div>
	  </div>
   </div>
</div>
<% end %>
</div>

app/views/articles/new.html.erb
<%= form_for @article, html: { :multipart => true } do |f| %>

<% if @article.errors.any? %>
	<strong><%= pluralize(@article.errors.count, 'error') %> found while saving images</strong>
	<ul>
		<% @article.errors.full_messages.each do |m|%>
			<li><%= m %></li>
		<% end %>
	</ul>
<% end %>

<%= f.label :title %>
<%= f.text_field :title%>

<br />

<%= f.label :content %>
<%= f.text_area :content, cols: 20, rows: 10 %>

<br />

<%= f.label :status %>
<%= f.radio_button :status, "active" %>
<%= label :article_status, 'active '%>
<%= f.radio_button :status, "off", :checked => true %>
<%= label :article_status, 'off'%>

<br />

<%= f.label :photo%>
<%= f.file_field :photo%>

<br />

<%= f.submit :submit %>
<% end %>

app/views/articles/profile.html.erb
<h1><%= @profile_name%> Profile</h1>

<!-- Content  -->
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h1> <%= @profile_name %> </h1>
          	<%= image_tag("profile2.JPG", alt: "Image Pgofile", width: "140px", height: "140px", class: "img-circle") %>
          	
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
         	<table class="table table-hover table-striped display">
         		<tbody>
         			<tr>
         				<th>Nama</th>
         				<td><%= @profile_name %></td>
         			</tr>
         			<tr>
         				<th>Tempat, Tanggal Lahir</th>
         				<td></td>
         			</tr>
         			<tr>
         				<th>Jenis Kelamin</th>
         				<td><%= @jenkel %></td>
         			</tr>
         			<tr>
         				<th>Alamat Domisili</th>
         				<td><%= @alamat %></td>
         			</tr>
         		</tbody>
         	</table>
         </div>
        </div>
      </div>
    </div>

app/views/articles/show.html.erb
<%= image_tag @article.photo.url(:original) %>

<h3><%= @article.title %></h3>
<p><%= @article.content%></p>
<p><%= link_to 'back to index', articles_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE-edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Task 3</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body style="padding-top: 60px;">
<!-- Navigation -->
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collape" data-targer=".navbar-collapse">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar" />
				<span class="icon-bar" />
				<span class="icon-bar" />
			</button>
			<span class="navbar-brand"><%= link_to 'Task 4', articles_path %></span>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', articles_path %></li>
				<li><%= link_to 'Profile', profile_path %></li>
				<li><%= link_to 'Contact', contact_path %></li>
			</ul>
		</div>
	</div>
</div>

<%= yield %>

</body>
</html>